### ISSUE TITLE
Text search doesn't seem to work

### ISSUE THREAD

**Issue by daaain** [a16z-infra/ai-getting-started#30] opened 2023-06-23 10:56 UTC
Not sure which part isn't working, but it can't pick up a question that is in the article word by word.

<img width="810" alt="Screenshot 2023-06-23 at 11 54 57" src="https://github.com/a16z-infra/ai-getting-started/assets/69962/97ae2738-5e81-4270-aa47-9fa2dfa11443">

<img width="1103" alt="Screenshot 2023-06-23 at 11 55 05" src="https://github.com/a16z-infra/ai-getting-started/assets/69962/cc5b1a73-9fc7-4e1e-8a2f-cbcb10dd9b5e">

**Comment by timqian** [comment] 2023-06-24 07:14
Meet the same issue, maybe the data on supabase is somehow lost? @ykhli 
<img width="528" alt="Screenshot 2023-06-24 at 15 12 56" src="https://github.com/a16z-infra/ai-getting-started/assets/5512552/6cf1958d-6faa-4d24-b7c3-486e82d1fdaf">
<img width="450" alt="Screenshot 2023-06-24 at 15 13 03" src="https://github.com/a16z-infra/ai-getting-started/assets/5512552/c767e841-c0c0-44bd-aaf2-4c42203a9605">

**Comment by ykhli** [comment] 2023-06-24 07:24
Ah you are right. I just re populated that table. try again to see if it works now?

**Comment by timqian** [comment] 2023-06-24 07:26
Works now!
![5C581735-4DBD-47C4-BBCF-064FF618D519](https://github.com/a16z-infra/ai-getting-started/assets/5512552/0e5d26d1-8c93-4021-a05c-81ce2b32b04d)

**Comment by ykhli** [comment] 2023-06-24 07:29
@timqian I think @daaain was referring to their local environment and not the demo instance. Since the answer to the question should not have been "I don't know". 

I suspect this is either because of the vector search results weren't optimal or because of chunking problems. Will look into this!

**Comment by daaain** [comment] 2023-06-24 10:02
I was looking at the demo instance, but if you could write up a few troubleshooting steps why this might be happening locally and how to fix it that would be really appreciated as I also would like to know how to run it! 😸

**Comment by gsmckenzie** [comment] 2023-06-24 10:02
I had this issue, but it was because I had run out of free OpenAI credits. It is worth checking the OpenAI usage (https://platform.openai.com/account/usage) to check that you have credits. No credits will also cause the embeddings to time out with a retries error. 

Obviously you issue may be different, but creating a new OpenAI account (with a different phone number) solved this for me.

**Comment by ykhli** [comment] 2023-06-25 22:50
Great @daaain I actually tried this locally and didn't reproduce the error locally. Also confirming this was fixed on the demo instance.

Thank you @gsmckenzie @daaain!!

**Closed** 2023-06-25 22:50 UTC
Labels: bug, triaging
